- name: Deploy devops-lab stack to WSL2
  hosts: app
  become: true

  tasks:
    - name: Ensure target directory exists
      file:
        path: /opt/devops-lab
        state: directory

    - name: Copy docker-compose file
      copy:
        src: files/docker-compose.yml
        dest: /opt/devops-lab/docker-compose.yml

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    # Не обязательно, но красиво: отдельно подтянуть образы
    - name: Pull images with docker-compose
      shell: docker-compose pull
      args:
        chdir: /opt/devops-lab

    - name: Run docker-compose up
      shell: docker-compose up -d --build
      args:
        chdir: /opt/devops-lab
